theme: kara
languageCode: "fr-CH"
title: "Enfants-Kara"
defaultContentLanguage: "fr"
enableRobotsTXT: true
disableKinds:
  - taxonomy
  - term
markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
params:
  description: "Association Enfants-Kara — Soutien aux enfants et jeunes au Togo depuis 2001."
