baseURL: "/"
languageCode: "fr-CH"
title: "Enfants-Kara"
defaultContentLanguage: "fr"
enableRobotsTXT: true
disableKinds:
  - taxonomy
  - term
caches:
  images:
    dir: :cacheDir/images
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  description: "Migration du site Enfants-Kara depuis Jimdo vers Hugo."
