# Environnement de développement local (hugo server --environment dev-local)
# baseURL non définie : hugo server injecte automatiquement l'adresse locale

params:
  cacheBust: true

minify:
  disableHTML: true
  disableCSS: true
  disableJS: true
  disableJSON: true
  disableSVG: true
  disableXML: true
